name: Build kernel
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Renaming kernel artifacts
        run: |
          # change dir
          echo "initial pwd"
          pwd

          cd ./asd/

          echo "new pwd"
          pwd

      - name: Renaming kernel artifacts
        run: |
          # append kernel type to downloaded artifacts
          echo "new jobs pwd"
          pwd
